- hosts: all
  vars:
      ansible_host_key_checking: false
  tasks:

    - name: copy war
      copy:
        src: /var/lib/jenkins/workspace/Deploy-Bootcamp_Advanced/target/bootcamp.war
        dest: /opt/docker/hanz/
    - name: copy dockerfile
      copy:
        src: /var/lib/jenkins/workspace/Deploy-Bootcamp_Advanced/Dockerfile
        dest: /opt/docker/hanz/
    - name: Stop current container
      docker_container:
        name: hanz-devops-container
        state: stopped
      ignore_errors: yes
    - name: remove stopped container
      docker_container: 
        name: hanz-devops-container
        state: absent
    - name: remover docker images # Clean up task
      docker_image: 
        name: hanz-devops-image:latest
        state: absent
    - name: create docker image using war file
      docker_image:
        name: hanz-devops-image:latest
        build:
          path: /opt/docker/hanz
        state: present
        source: build
    - name: run container
      docker_container:
       name: hanz-devops-container
       state: started
       image: hanz-devops-image:latest
       detach: yes
       ports:
        - "8081:8080"