- hosts: all
  vars:
      ansible_host_key_checking: false
  tasks:

    - name: copy war
      copy:
        src: /var/lib/jenkins/workspace/Hanz-Deploy_on_Container/webapp/target/webapp.war
        dest: /opt/docker/hanz/
    - name: Stop current container
      community.docker.docker_container:
        name: hanz-devops-container
        state: stopped
      ignore_errors: yes
    